/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v15.0
processor: MC56F83783
package_id: MC56F83783VLH
mcu_data: ksdk2_0
processor_version: 15.0.0
pin_labels:
- {pin_num: '46', pin_signal: GPIOE1/PWMA_0A/XB_OUT5, label: PWMA0A}
- {pin_num: '45', pin_signal: GPIOE0/PWMA_0B/XB_OUT4, label: PWMA0B}
- {pin_num: '48', pin_signal: GPIOE3/PWMA_1A/XB_OUT7, label: PWMA1A}
- {pin_num: '47', pin_signal: GPIOE2/PWMA_1B/XB_OUT6, label: PWMA1B}
- {pin_num: '15', pin_signal: GPIOA2/ANA2/VREFHA/CMPA_IN1, label: Vbat}
- {pin_num: '16', pin_signal: GPIOA3/ANA3/VREFLA/CMPA_IN2, label: Vbus}
- {pin_num: '9', pin_signal: GPIOA7/ANA7, label: Vhv}
- {pin_num: '24', pin_signal: GPIOB0/ANB0/CMPB_IN3, label: Ibat}
- {pin_num: '25', pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O, label: Ibuck}
- {pin_num: '17', pin_signal: GPIOB7/ANB7/CMPB_IN2, label: Iboost}
- {pin_num: '14', pin_signal: GPIOA1/ANA1/CMPA_IN0, label: Ir_lv(+)}
- {pin_num: '13', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O, label: Vds_SR1}
- {pin_num: '19', pin_signal: GPIOB6/ANB6/CMPB_IN1, label: Ihv}
- {pin_num: '21', pin_signal: GPIOB4/ANB4/CMPC_IN1, label: Ir_lv(-)}
- {pin_num: '20', pin_signal: GPIOB5/ANB5/CMPC_IN2, label: Vr_hv(-)}
- {pin_num: '27', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3, label: Vds_SR2}
- {pin_num: '12', pin_signal: GPIOA4/ANA4/CMPD_IN0, label: Vr_hv(+)}
- {pin_num: '59', pin_signal: GPIOF7/TB3/CMPC_O/XB_IN3, label: Load_SW, identifier: Load_SW}
- {pin_num: '56', pin_signal: GPIOC15/SCL0/XB_OUT5/PWMA_FAULT5, label: STB_EN, identifier: STB_EN}
- {pin_num: '3', pin_signal: GPIOC0/EXTAL/CLKIN0, label: User_LED, identifier: User_LED}
- {pin_num: '33', pin_signal: GPIOC8/MISO0/RXD0/XB_IN9, label: User_LED1, identifier: User_LED1}
- {pin_num: '49', pin_signal: GPIOC13/TA3/XB_IN6/EWM_OUT_B, label: XBAR_TP1, identifier: XBAR_TP1}
- {pin_num: '18', pin_signal: GPIOC5/DACA_O/XB_IN7, label: XBAR_TP2, identifier: XBAR_TP2}
- {pin_num: '36', pin_signal: GPIOF0/XB_IN6/TB2, label: XBAR_TP3, identifier: XBAR_TP3}
- {pin_num: '32', pin_signal: GPIOC7/SS0_B/TXD0/XB_IN8/XB_OUT6, label: XBAR_TP4, identifier: XBAR_TP4}
- {pin_num: '52', pin_signal: GPIOE5/PWMA_2A/XB_IN3/XB_OUT9, label: PWMA2A}
- {pin_num: '53', pin_signal: GPIOE6/PWMA_3B/XB_IN4/PWMB_2B/XB_OUT10, label: PWMA3B}
- {pin_num: '51', pin_signal: GPIOE4/PWMA_2B/XB_IN2/XB_OUT8, label: PWMA2B}
- {pin_num: '54', pin_signal: GPIOE7/PWMA_3A/XB_IN5/PWMB_2A/XB_OUT11, label: PWMA3A}
- {pin_num: '34', pin_signal: GPIOC9/SCLK0/XB_IN4/TXD0/XB_OUT8, label: XBAR_TP5, identifier: XBAR_TP5}
- {pin_num: '4', pin_signal: GPIOC1/XTAL, label: LED_HVP, identifier: LED_HVP}
- {pin_num: '58', pin_signal: GPIOF6/TB2/PWMA_3X/PWMB_3X/XB_IN2, label: TEMP_HV}
- {pin_num: '8', pin_signal: GPIOC4/TA1/CMPB_O/XB_IN8/EWM_OUT_B, label: TEMP_LV}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_sim.h"
#include "fsl_gpio.h"
#include "fsl_xbara.h"
#include "pin_mux.h"

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins(void)
{
    Common_Config_Pin();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BCM_Config_Pin:
- options: {createDeInit: 'true', callFromInitBoot: 'false', prefix: BOARD_, coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '53', peripheral: EVTG, signal: 'EVTG1_OUT, B', pin_signal: GPIOE6/PWMA_3B/XB_IN4/PWMB_2B/XB_OUT10}
  - {pin_num: '52', peripheral: EVTG, signal: 'EVTG1_OUT, A', pin_signal: GPIOE5/PWMA_2A/XB_IN3/XB_OUT9}
  - {peripheral: EVTG, signal: 'EVTG2, B', pin_signal: CMPC_OUT}
  - {peripheral: EVTG, signal: 'EVTG2, A', pin_signal: PWMA3_MUX_TRIG0}
  - {peripheral: EVTG, signal: 'EVTG1, B', pin_signal: CMPA_OUT}
  - {peripheral: EVTG, signal: 'EVTG1, A', pin_signal: PWMA2_MUX_TRIG0}
  - {peripheral: CMPC, signal: WIN_SMP, pin_signal: EVTG0_OUTB}
  - {peripheral: CMPA, signal: WIN_SMP, pin_signal: EVTG0_OUTA}
  - {peripheral: EVTG, signal: 'EVTG0, D', pin_signal: TA3_OUT}
  - {peripheral: EVTG, signal: 'EVTG0, C', pin_signal: TA2_OUT}
  - {peripheral: EVTG, signal: 'EVTG0, B', pin_signal: TA1_OUT}
  - {peripheral: EVTG, signal: 'EVTG0, A', pin_signal: TA0_OUT}
  - {peripheral: PWMA, signal: 'FAULT, 0', pin_signal: CMPB_OUT}
  - {peripheral: TMRA, signal: 'IN, 1', pin_signal: CMPC_OUT}
  - {peripheral: TMRA, signal: 'IN, 0', pin_signal: CMPA_OUT}
  - {pin_num: '46', peripheral: PWMA, signal: 'A, 0', pin_signal: GPIOE1/PWMA_0A/XB_OUT5}
  - {pin_num: '45', peripheral: PWMA, signal: 'B, 0', pin_signal: GPIOE0/PWMA_0B/XB_OUT4}
  - {pin_num: '48', peripheral: PWMA, signal: 'A, 1', pin_signal: GPIOE3/PWMA_1A/XB_OUT7}
  - {pin_num: '47', peripheral: PWMA, signal: 'B, 1', pin_signal: GPIOE2/PWMA_1B/XB_OUT6}
  - {pin_num: '51', peripheral: EVTG, signal: 'EVTG2_OUT, A', pin_signal: GPIOE4/PWMA_2B/XB_IN2/XB_OUT8}
  - {pin_num: '54', peripheral: EVTG, signal: 'EVTG2_OUT, B', pin_signal: GPIOE7/PWMA_3A/XB_IN5/PWMB_2A/XB_OUT11}
  - {pin_num: '59', peripheral: GPIOF, signal: 'GPIO, 7', pin_signal: GPIOF7/TB3/CMPC_O/XB_IN3, direction: OUTPUT}
  - {pin_num: '56', peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: GPIOC15/SCL0/XB_OUT5/PWMA_FAULT5, direction: OUTPUT}
  - {pin_num: '3', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: GPIOC0/EXTAL/CLKIN0, direction: OUTPUT}
  - {pin_num: '33', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: GPIOC8/MISO0/RXD0/XB_IN9, direction: OUTPUT}
  - {pin_num: '49', peripheral: GPIOC, signal: 'GPIO, 13', pin_signal: GPIOC13/TA3/XB_IN6/EWM_OUT_B, direction: OUTPUT}
  - {pin_num: '18', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: GPIOC5/DACA_O/XB_IN7, direction: OUTPUT}
  - {pin_num: '36', peripheral: GPIOF, signal: 'GPIO, 0', pin_signal: GPIOF0/XB_IN6/TB2, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: GPIOC1/XTAL, direction: OUTPUT}
  - {peripheral: ADC, signal: 'SYNC, A', pin_signal: PWMA0_MUX_TRIG0}
  - {pin_num: '32', peripheral: EVTG, signal: 'EVTG0_OUT, A', pin_signal: GPIOC7/SS0_B/TXD0/XB_IN8/XB_OUT6}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BCM_Config_Pin
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BCM_Config_Pin(void)
{
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOE IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOE);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* GPIO functionality on pin GPIOC0 (pin 3) */
    GPIO_PinSetPeripheralMode(BOARD_User_LED_GPIO, BOARD_User_LED_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC1 (pin 4) */
    GPIO_PinSetPeripheralMode(BOARD_LED_HVP_GPIO, BOARD_LED_HVP_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC5 (pin 18) */
    GPIO_PinSetPeripheralMode(BOARD_XBAR_TP2_GPIO, BOARD_XBAR_TP2_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOC7 (pin 32) */
    GPIO_PinSetPeripheralMode(BOARD_XBAR_TP4_GPIO, BOARD_XBAR_TP4_PIN_MASK, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC7 (pin 32) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C7_XB_OUT6);
    /* GPIO functionality on pin GPIOC8 (pin 33) */
    GPIO_PinSetPeripheralMode(BOARD_User_LED1_GPIO, BOARD_User_LED1_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC13 (pin 49) */
    GPIO_PinSetPeripheralMode(BOARD_XBAR_TP1_GPIO, BOARD_XBAR_TP1_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC15 (pin 56) */
    GPIO_PinSetPeripheralMode(BOARD_STB_EN_GPIO, BOARD_STB_EN_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E0_PWMA_0B);
    /* Enable peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E1_PWMA_0A);
    /* Enable peripheral functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E2_PWMA_1B);
    /* Enable peripheral functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E3_PWMA_1A);
    /* Enable peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E4_XB_OUT8);
    /* Enable peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E5_XB_OUT9);
    /* Enable peripheral functionality on pin GPIOE6 (pin 53) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin6, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE6 (pin 53) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E6_XB_OUT10);
    /* Enable peripheral functionality on pin GPIOE7 (pin 54) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin7, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE7 (pin 54) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E7_XB_OUT11);
    /* GPIO functionality on pin GPIOF0 (pin 36) */
    GPIO_PinSetPeripheralMode(BOARD_XBAR_TP3_GPIO, BOARD_XBAR_TP3_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF7 (pin 59) */
    GPIO_PinSetPeripheralMode(BOARD_Load_SW_GPIO, BOARD_Load_SW_PIN_MASK, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOC0 (pin 3)  */
    GPIO_PinWrite(BOARD_User_LED_GPIO, BOARD_User_LED_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_User_LED_GPIO, BOARD_User_LED_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC1 (pin 4)  */
    GPIO_PinWrite(BOARD_LED_HVP_GPIO, BOARD_LED_HVP_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_LED_HVP_GPIO, BOARD_LED_HVP_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC5 (pin 18)  */
    GPIO_PinWrite(BOARD_XBAR_TP2_GPIO, BOARD_XBAR_TP2_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_XBAR_TP2_GPIO, BOARD_XBAR_TP2_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC8 (pin 33)  */
    GPIO_PinWrite(BOARD_User_LED1_GPIO, BOARD_User_LED1_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_User_LED1_GPIO, BOARD_User_LED1_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC13 (pin 49)  */
    GPIO_PinWrite(BOARD_XBAR_TP1_GPIO, BOARD_XBAR_TP1_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_XBAR_TP1_GPIO, BOARD_XBAR_TP1_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC15 (pin 56)  */
    GPIO_PinWrite(BOARD_STB_EN_GPIO, BOARD_STB_EN_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_STB_EN_GPIO, BOARD_STB_EN_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF0 (pin 36)  */
    GPIO_PinWrite(BOARD_XBAR_TP3_GPIO, BOARD_XBAR_TP3_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_XBAR_TP3_GPIO, BOARD_XBAR_TP3_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF7 (pin 59)  */
    GPIO_PinWrite(BOARD_Load_SW_GPIO, BOARD_Load_SW_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BOARD_Load_SW_GPIO, BOARD_Load_SW_PIN_MASK, kGPIO_DigitalOutput);

    /* ADC and TMR Select */
    /* xbar input 36.: xbar input 36, TMRA0. */
    SIM_SetXbarInputAdcTmrSelection(SIM, kSIM_XBARIN36Index, kSIM_XBARIN36TMRA0);
    /* xbar input 37.: xbar input 37, TMRA1. */
    SIM_SetXbarInputAdcTmrSelection(SIM, kSIM_XBARIN37Index, kSIM_XBARIN37TMRA1);
    /* xbar input 38.: xbar input 38, TMRA2. */
    SIM_SetXbarInputAdcTmrSelection(SIM, kSIM_XBARIN38Index, kSIM_XBARIN38TMRA2);
    /* xbar input 39.: xbar input 39, TMRA3. */
    SIM_SetXbarInputAdcTmrSelection(SIM, kSIM_XBARIN39Index, kSIM_XBARIN39TMRA3);

    /* Internal Peripheral Select */
    /* Select PWMA Fault 0 Input.: Select PWMA Fault 0 Input, XB_OUT29. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault0InputIndex, kSIM_PWMAFault0Input_XB_OUT29);
    /* Select TMRA0 Input.: Select TMRA0 Input, XB_OUT38. */
    SIM_SetInternalPeriInput(SIM, kSIM_TMRA0InputIndex, kSIM_TMRA0Input_XB_OUT38);
    /* Select TMRA1 Input.: Select TMRA1 Input, XB_OUT39. */
    SIM_SetInternalPeriInput(SIM, kSIM_TMRA1InputIndex, kSIM_TMRA1Input_XB_OUT39);

    /* PWM Select */
    /* xbar input 20.: xbar input 20, PWMA0_MUX_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN20Index, kSIM_XbarIn20PWMA0MuxTrig0);
    /* xbar input 24.: xbar input 24, PWMA2_MUX_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN24Index, kSIM_XbarIn24PWMA2MuxTrig0);
    /* xbar input 26.: xbar input 26, PWMA3_MUX_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN26Index, kSIM_XbarIn26PWMA3MuxTrig0);

    /* CMPB_OUT output assigned to XBARA_IN13 input is connected
     * to XBARA_OUT29 output assigned to PWMA_PWMB_FAULT0 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpbOut, kXBARA_OutputPwmaPwmbFault0);
    /* CMPA_OUT output assigned to XBARA_IN12 input is connected
     * to XBARA_OUT38 output assigned to TA0_IN */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpaOut, kXBARA_OutputTa0In);
    /* CMPC_OUT output assigned to XBARA_IN14 input is connected
     * to XBARA_OUT39 output assigned to TA1_IN */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpcOut, kXBARA_OutputTa1In);
    /* AN0_LIMIT_TA0_OUT output assigned to XBARA_IN36 input is connected
     * to XBARA_OUT47 output assigned to EVTG0_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputAn0LimitTa0Out, kXBARA_OutputEvtg0A);
    /* AN1_LIMIT_TA1_OUT output assigned to XBARA_IN37 input is connected
     * to XBARA_OUT48 output assigned to EVTG0_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputAn1LimitTa1Out, kXBARA_OutputEvtg0B);
    /* AN2_LIMIT_TA2_OUT output assigned to XBARA_IN38 input is connected
     * to XBARA_OUT49 output assigned to EVTG0_C */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputAn2LimitTa2Out, kXBARA_OutputEvtg0C);
    /* AN3_LIMIT_TA3_OUT output assigned to XBARA_IN39 input is connected
     * to XBARA_OUT50 output assigned to EVTG0_D */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputAn3LimitTa3Out, kXBARA_OutputEvtg0D);
    /* PWMA2_MUX_PWMB2_OUT_TRIG0 output assigned to XBARA_IN24 input is connected
     * to XBARA_OUT51 output assigned to EVTG1_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma2MuxPwmb2OutTrig0, kXBARA_OutputEvtg1A);
    /* CMPA_OUT output assigned to XBARA_IN12 input is connected
     * to XBARA_OUT52 output assigned to EVTG1_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpaOut, kXBARA_OutputEvtg1B);
    /* PWMA3_MUX_PWMB3_OUT_TRIG0 output assigned to XBARA_IN26 input is connected
     * to XBARA_OUT55 output assigned to EVTG2_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma3MuxPwmb3OutTrig0, kXBARA_OutputEvtg2A);
    /* CMPC_OUT output assigned to XBARA_IN14 input is connected
     * to XBARA_OUT56 output assigned to EVTG2_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpcOut, kXBARA_OutputEvtg2B);
    /* EVTG0_OUTA output assigned to XBARA_IN40 input is connected
     * to XBARA_OUT6 output assigned to XB_OUT6 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg0Outa, kXBARA_OutputXbOut6);
    /* EVTG2_OUTA output assigned to XBARA_IN42 input is connected
     * to XBARA_OUT8 output assigned to XB_OUT8 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg2Outa, kXBARA_OutputXbOut8);
    /* EVTG1_OUTA output assigned to XBARA_IN41 input is connected
     * to XBARA_OUT9 output assigned to XB_OUT9 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg1Outa, kXBARA_OutputXbOut9);
    /* EVTG1_OUTB output assigned to XBARA_IN47 input is connected
     * to XBARA_OUT10 output assigned to XB_OUT10 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg1Outb, kXBARA_OutputXbOut10);
    /* EVTG2_OUTB output assigned to XBARA_IN48 input is connected
     * to XBARA_OUT11 output assigned to XB_OUT11 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg2Outb, kXBARA_OutputXbOut11);
    /* PWMA0_MUX_PWMB0_OUT_TRIG0 output assigned to XBARA_IN20 input is connected
     * to XBARA_OUT12 output assigned to ADCA_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma0MuxPwmb0OutTrig0, kXBARA_OutputAdcaSync);
    /* EVTG0_OUTA output assigned to XBARA_IN40 input is connected
     * to XBARA_OUT16 output assigned to CMPA */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg0Outa, kXBARA_OutputCmpa);
    /* EVTG0_OUTB output assigned to XBARA_IN46 input is connected
     * to XBARA_OUT18 output assigned to CMPC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg0Outb, kXBARA_OutputCmpc);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BCM_Config_Pin_deinit
 * Description   : This is a de-initialization function for 'BCM_Config_Pin' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 * END ****************************************************************************************************************/
void BCM_Config_Pin_deinit(void)
{
    /* There are conflicts or other incorrect settings in the configuration, the code below is generated only for 
     * those registers which are set correctly and without a conflict. Open this file in Pins Tool for more details. */

    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOE IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOE);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* GPIO functionality on pin GPIOC0 (pin 3) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin0, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC1 (pin 4) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin1, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC5 (pin 18) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin5, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC7 (pin 32) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin7, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC8 (pin 33) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin8, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC13 (pin 49) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin13, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC15 (pin 56) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin15, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin0, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin1, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin2, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin3, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin4, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin5, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE6 (pin 53) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin6, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE7 (pin 54) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin7, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF0 (pin 36) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin0, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF7 (pin 59) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin7, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOC0 (pin 3)  */
    GPIO_PinSetDirection(GPIOC, kGPIO_Pin0, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC1 (pin 4)  */
    GPIO_PinSetDirection(GPIOC, kGPIO_Pin1, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC5 (pin 18)  */
    GPIO_PinSetDirection(GPIOC, kGPIO_Pin5, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC7 (pin 32)  */
    GPIO_PinSetDirection(GPIOC, kGPIO_Pin7, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC8 (pin 33)  */
    GPIO_PinSetDirection(GPIOC, kGPIO_Pin8, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC13 (pin 49)  */
    GPIO_PinSetDirection(GPIOC, kGPIO_Pin13, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC15 (pin 56)  */
    GPIO_PinSetDirection(GPIOC, kGPIO_Pin15, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE0 (pin 45)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin0, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE1 (pin 46)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin1, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE2 (pin 47)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin2, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE3 (pin 48)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin3, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE4 (pin 51)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin4, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE5 (pin 52)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin5, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE6 (pin 53)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin6, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE7 (pin 54)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin7, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOF0 (pin 36)  */
    GPIO_PinSetDirection(GPIOF, kGPIO_Pin0, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOF7 (pin 59)  */
    GPIO_PinSetDirection(GPIOF, kGPIO_Pin7, kGPIO_DigitalInput);

    /* Pin configuration on GPIOC0 (pin 3) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOC, kGPIO_Pin0, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOC, kGPIO_Pin0, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOC, kGPIO_Pin0, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC1 (pin 4) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOC, kGPIO_Pin1, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOC, kGPIO_Pin1, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOC, kGPIO_Pin1, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC5 (pin 18) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOC, kGPIO_Pin5, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOC, kGPIO_Pin5, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOC, kGPIO_Pin5, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC7 (pin 32) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOC, kGPIO_Pin7, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOC, kGPIO_Pin7, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOC, kGPIO_Pin7, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC8 (pin 33) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOC, kGPIO_Pin8, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOC, kGPIO_Pin8, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOC, kGPIO_Pin8, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC13 (pin 49) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOC, kGPIO_Pin13, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOC, kGPIO_Pin13, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOC, kGPIO_Pin13, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC15 (pin 56) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOC, kGPIO_Pin15, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOC, kGPIO_Pin15, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOC, kGPIO_Pin15, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE0 (pin 45) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin0, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin0, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin0, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE1 (pin 46) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin1, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin1, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin1, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE2 (pin 47) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin2, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin2, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin2, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE3 (pin 48) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin3, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin3, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin3, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE4 (pin 51) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin4, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin4, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin4, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE5 (pin 52) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin5, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin5, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin5, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE6 (pin 53) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin6, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin6, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin6, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE7 (pin 54) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin7, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin7, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin7, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOF0 (pin 36) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOF, kGPIO_Pin0, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOF, kGPIO_Pin0, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOF, kGPIO_Pin0, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOF7 (pin 59) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOF, kGPIO_Pin7, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOF, kGPIO_Pin7, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOF, kGPIO_Pin7, kGPIO_SlewRateSlow);

    /* Interrupt configuration on GPIOC0 (pin 3): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOC, kGPIO_Pin0, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC1 (pin 4): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOC, kGPIO_Pin1, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC5 (pin 18): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOC, kGPIO_Pin5, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC7 (pin 32): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOC, kGPIO_Pin7, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC8 (pin 33): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOC, kGPIO_Pin8, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC13 (pin 49): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOC, kGPIO_Pin13, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC15 (pin 56): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOC, kGPIO_Pin15, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE0 (pin 45): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin0, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE1 (pin 46): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin1, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE2 (pin 47): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin2, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE3 (pin 48): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin3, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE4 (pin 51): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin4, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE5 (pin 52): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin5, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE6 (pin 53): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin6, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE7 (pin 54): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin7, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOF0 (pin 36): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOF, kGPIO_Pin0, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOF7 (pin 59): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOF, kGPIO_Pin7, kGPIO_InterruptDisable);

    GPIOC->PUR =
        ((GPIOC->PUR &
          /* Mask bits to zero which are setting */
          (~(GPIO_PUR_PU_0_MASK | GPIO_PUR_PU_1_MASK | GPIO_PUR_PU_5_MASK | GPIO_PUR_PU_7_MASK | GPIO_PUR_PU_8_MASK | GPIO_PUR_PU_13_MASK | GPIO_PUR_PU_15_MASK)))

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_0_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_1_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_5_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_7_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_8_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_13_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_15_DISABLED));

    GPIOC->PUS =
        ((GPIOC->PUS &
          /* Mask bits to zero which are setting */
          (~(GPIO_PUS_PUS_0_MASK | GPIO_PUS_PUS_1_MASK | GPIO_PUS_PUS_5_MASK | GPIO_PUS_PUS_7_MASK | GPIO_PUS_PUS_8_MASK | GPIO_PUS_PUS_13_MASK | GPIO_PUS_PUS_15_MASK)))

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_0_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_1_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_5_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_7_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_8_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_13_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_15_PULLUP));

    GPIOE->PUR =
        ((GPIOE->PUR &
          /* Mask bits to zero which are setting */
          (~(GPIO_PUR_PU_0_MASK | GPIO_PUR_PU_1_MASK | GPIO_PUR_PU_2_MASK | GPIO_PUR_PU_3_MASK | GPIO_PUR_PU_4_MASK | GPIO_PUR_PU_5_MASK | GPIO_PUR_PU_6_MASK | GPIO_PUR_PU_7_MASK)))

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_0_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_1_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_2_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_3_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_4_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_5_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_6_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_7_DISABLED));

    GPIOE->PUS =
        ((GPIOE->PUS &
          /* Mask bits to zero which are setting */
          (~(GPIO_PUS_PUS_0_MASK | GPIO_PUS_PUS_1_MASK | GPIO_PUS_PUS_2_MASK | GPIO_PUS_PUS_3_MASK | GPIO_PUS_PUS_4_MASK | GPIO_PUS_PUS_5_MASK | GPIO_PUS_PUS_6_MASK | GPIO_PUS_PUS_7_MASK)))

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_0_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_1_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_2_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_3_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_4_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_5_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_6_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_7_PULLUP));

    GPIOF->PUR = ((GPIOF->PUR &
                   /* Mask bits to zero which are setting */
                   (~(GPIO_PUR_PU_0_MASK | GPIO_PUR_PU_7_MASK)))

                  /* Pull Resistor Enable Bits: Pull resistor is disabled. */
                  | GPIO_PUR_PU(PUR_PU_0_DISABLED)

                  /* Pull Resistor Enable Bits: Pull resistor is disabled. */
                  | GPIO_PUR_PU(PUR_PU_7_DISABLED));

    GPIOF->PUS = ((GPIOF->PUS &
                   /* Mask bits to zero which are setting */
                   (~(GPIO_PUS_PUS_0_MASK | GPIO_PUS_PUS_7_MASK)))

                  /* Pull Resistor Type Select Bits: Pullup resistor. */
                  | GPIO_PUS_PUS(PUS_PUS_0_PULLUP)

                  /* Pull Resistor Type Select Bits: Pullup resistor. */
                  | GPIO_PUS_PUS(PUS_PUS_7_PULLUP));
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT47 output assigned to EVTG0_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg0A);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT48 output assigned to EVTG0_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg0B);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT49 output assigned to EVTG0_C */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg0C);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT50 output assigned to EVTG0_D */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg0D);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT51 output assigned to EVTG1_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg1A);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT52 output assigned to EVTG1_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg1B);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT55 output assigned to EVTG2_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg2A);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT56 output assigned to EVTG2_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg2B);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT12 output assigned to ADCA_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputAdcaSync);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT16 output assigned to CMPA */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputCmpa);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT18 output assigned to CMPC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputCmpc);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BDM_Config_Pin:
- options: {createDeInit: 'true', callFromInitBoot: 'false', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '36', peripheral: GPIOF, signal: 'GPIO, 0', pin_signal: GPIOF0/XB_IN6/TB2, direction: OUTPUT}
  - {pin_num: '59', peripheral: GPIOF, signal: 'GPIO, 7', pin_signal: GPIOF7/TB3/CMPC_O/XB_IN3, direction: OUTPUT}
  - {pin_num: '3', peripheral: GPIOC, signal: 'GPIO, 0', pin_signal: GPIOC0/EXTAL/CLKIN0, direction: OUTPUT}
  - {pin_num: '4', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: GPIOC1/XTAL, direction: OUTPUT}
  - {pin_num: '18', peripheral: GPIOC, signal: 'GPIO, 5', pin_signal: GPIOC5/DACA_O/XB_IN7, direction: OUTPUT}
  - {pin_num: '33', peripheral: GPIOC, signal: 'GPIO, 8', pin_signal: GPIOC8/MISO0/RXD0/XB_IN9, direction: OUTPUT}
  - {pin_num: '49', peripheral: GPIOC, signal: 'GPIO, 13', pin_signal: GPIOC13/TA3/XB_IN6/EWM_OUT_B, direction: OUTPUT}
  - {pin_num: '56', peripheral: GPIOC, signal: 'GPIO, 15', pin_signal: GPIOC15/SCL0/XB_OUT5/PWMA_FAULT5, direction: OUTPUT}
  - {pin_num: '52', peripheral: PWMA, signal: 'A, 2', pin_signal: GPIOE5/PWMA_2A/XB_IN3/XB_OUT9}
  - {pin_num: '51', peripheral: PWMA, signal: 'B, 2', pin_signal: GPIOE4/PWMA_2B/XB_IN2/XB_OUT8}
  - {pin_num: '54', peripheral: PWMA, signal: 'A, 3', pin_signal: GPIOE7/PWMA_3A/XB_IN5/PWMB_2A/XB_OUT11}
  - {pin_num: '53', peripheral: PWMA, signal: 'B, 3', pin_signal: GPIOE6/PWMA_3B/XB_IN4/PWMB_2B/XB_OUT10}
  - {peripheral: EVTG, signal: 'EVTG1, A', pin_signal: PWMA0_MUX_TRIG0}
  - {peripheral: EVTG, signal: 'EVTG1, B', pin_signal: CMPC_OUT}
  - {peripheral: EVTG, signal: 'EVTG2, A', pin_signal: PWMA1_MUX_TRIG0}
  - {peripheral: EVTG, signal: 'EVTG2, B', pin_signal: CMPD_OUT}
  - {pin_num: '46', peripheral: EVTG, signal: 'EVTG1_OUT, A', pin_signal: GPIOE1/PWMA_0A/XB_OUT5}
  - {pin_num: '47', peripheral: EVTG, signal: 'EVTG1_OUT, B', pin_signal: GPIOE2/PWMA_1B/XB_OUT6}
  - {pin_num: '45', peripheral: EVTG, signal: 'EVTG2_OUT, A', pin_signal: GPIOE0/PWMA_0B/XB_OUT4}
  - {pin_num: '48', peripheral: EVTG, signal: 'EVTG2_OUT, B', pin_signal: GPIOE3/PWMA_1A/XB_OUT7}
  - {peripheral: ADC, signal: 'SYNC, A', pin_signal: PWMA2_MUX_TRIG0}
  - {pin_num: '50', peripheral: PWMA, signal: 'FAULT, 0', pin_signal: GPIOF1/CLKO1/XB_IN7/CMPD_O}
  - {peripheral: PWMA, signal: 'EXT_SYNC, 3', pin_signal: PWMA0_MUX_TRIG1}
  - {peripheral: TMRA, signal: 'IN, 0', pin_signal: CMPC_OUT}
  - {peripheral: TMRA, signal: 'IN, 1', pin_signal: CMPD_OUT}
  - {peripheral: EVTG, signal: 'EVTG0, A', pin_signal: TA0_OUT}
  - {peripheral: EVTG, signal: 'EVTG0, B', pin_signal: TA1_OUT}
  - {peripheral: EVTG, signal: 'EVTG0, C', pin_signal: TA2_OUT}
  - {peripheral: EVTG, signal: 'EVTG0, D', pin_signal: TA3_OUT}
  - {peripheral: CMPC, signal: WIN_SMP, pin_signal: EVTG0_OUTB}
  - {peripheral: CMPD, signal: WIN_SMP, pin_signal: EVTG0_OUTA}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BDM_Config_Pin
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void BDM_Config_Pin(void)
{
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOE IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOE);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* GPIO functionality on pin GPIOC0 (pin 3) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_User_LED_GPIO, BDM_CONFIG_PIN_User_LED_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC1 (pin 4) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_LED_HVP_GPIO, BDM_CONFIG_PIN_LED_HVP_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC5 (pin 18) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_XBAR_TP2_GPIO, BDM_CONFIG_PIN_XBAR_TP2_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC8 (pin 33) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_User_LED1_GPIO, BDM_CONFIG_PIN_User_LED1_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC13 (pin 49) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_XBAR_TP1_GPIO, BDM_CONFIG_PIN_XBAR_TP1_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC15 (pin 56) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_STB_EN_GPIO, BDM_CONFIG_PIN_STB_EN_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E0_XB_OUT4);
    /* Enable peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E1_XB_OUT5);
    /* Enable peripheral functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E2_XB_OUT6);
    /* Enable peripheral functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E3_XB_OUT7);
    /* Enable peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E4_PWMA_2B);
    /* Enable peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E5_PWMA_2A);
    /* Enable peripheral functionality on pin GPIOE6 (pin 53) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin6, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE6 (pin 53) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E6_PWMA_3B);
    /* Enable peripheral functionality on pin GPIOE7 (pin 54) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin7, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOE7 (pin 54) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_E7_PWMA_3A);
    /* GPIO functionality on pin GPIOF0 (pin 36) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_XBAR_TP3_GPIO, BDM_CONFIG_PIN_XBAR_TP3_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOF1 (pin 50) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF1 (pin 50) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F1_XB_IN7);
    /* GPIO functionality on pin GPIOF7 (pin 59) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_Load_SW_GPIO, BDM_CONFIG_PIN_Load_SW_PIN_MASK, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOC0 (pin 3)  */
    GPIO_PinWrite(BDM_CONFIG_PIN_User_LED_GPIO, BDM_CONFIG_PIN_User_LED_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BDM_CONFIG_PIN_User_LED_GPIO, BDM_CONFIG_PIN_User_LED_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC1 (pin 4)  */
    GPIO_PinWrite(BDM_CONFIG_PIN_LED_HVP_GPIO, BDM_CONFIG_PIN_LED_HVP_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BDM_CONFIG_PIN_LED_HVP_GPIO, BDM_CONFIG_PIN_LED_HVP_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC5 (pin 18)  */
    GPIO_PinWrite(BDM_CONFIG_PIN_XBAR_TP2_GPIO, BDM_CONFIG_PIN_XBAR_TP2_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BDM_CONFIG_PIN_XBAR_TP2_GPIO, BDM_CONFIG_PIN_XBAR_TP2_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC8 (pin 33)  */
    GPIO_PinWrite(BDM_CONFIG_PIN_User_LED1_GPIO, BDM_CONFIG_PIN_User_LED1_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BDM_CONFIG_PIN_User_LED1_GPIO, BDM_CONFIG_PIN_User_LED1_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC13 (pin 49)  */
    GPIO_PinWrite(BDM_CONFIG_PIN_XBAR_TP1_GPIO, BDM_CONFIG_PIN_XBAR_TP1_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BDM_CONFIG_PIN_XBAR_TP1_GPIO, BDM_CONFIG_PIN_XBAR_TP1_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOC15 (pin 56)  */
    GPIO_PinWrite(BDM_CONFIG_PIN_STB_EN_GPIO, BDM_CONFIG_PIN_STB_EN_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BDM_CONFIG_PIN_STB_EN_GPIO, BDM_CONFIG_PIN_STB_EN_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF0 (pin 36)  */
    GPIO_PinWrite(BDM_CONFIG_PIN_XBAR_TP3_GPIO, BDM_CONFIG_PIN_XBAR_TP3_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BDM_CONFIG_PIN_XBAR_TP3_GPIO, BDM_CONFIG_PIN_XBAR_TP3_PIN_MASK, kGPIO_DigitalOutput);

    /* Initialize GPIO functionality on pin GPIOF7 (pin 59)  */
    GPIO_PinWrite(BDM_CONFIG_PIN_Load_SW_GPIO, BDM_CONFIG_PIN_Load_SW_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(BDM_CONFIG_PIN_Load_SW_GPIO, BDM_CONFIG_PIN_Load_SW_PIN_MASK, kGPIO_DigitalOutput);

    /* ADC and TMR Select */
    /* xbar input 36.: xbar input 36, TMRA0. */
    SIM_SetXbarInputAdcTmrSelection(SIM, kSIM_XBARIN36Index, kSIM_XBARIN36TMRA0);
    /* xbar input 37.: xbar input 37, TMRA1. */
    SIM_SetXbarInputAdcTmrSelection(SIM, kSIM_XBARIN37Index, kSIM_XBARIN37TMRA1);
    /* xbar input 38.: xbar input 38, TMRA2. */
    SIM_SetXbarInputAdcTmrSelection(SIM, kSIM_XBARIN38Index, kSIM_XBARIN38TMRA2);
    /* xbar input 39.: xbar input 39, TMRA3. */
    SIM_SetXbarInputAdcTmrSelection(SIM, kSIM_XBARIN39Index, kSIM_XBARIN39TMRA3);

    /* Internal Peripheral Select */
    /* Select PWMA Fault 0 Input.: Select PWMA Fault 0 Input, XB_OUT29. */
    SIM_SetInternalPeriInput(SIM, kSIM_PWMAFault0InputIndex, kSIM_PWMAFault0Input_XB_OUT29);
    /* Select TMRA0 Input.: Select TMRA0 Input, XB_OUT38. */
    SIM_SetInternalPeriInput(SIM, kSIM_TMRA0InputIndex, kSIM_TMRA0Input_XB_OUT38);
    /* Select TMRA1 Input.: Select TMRA1 Input, XB_OUT39. */
    SIM_SetInternalPeriInput(SIM, kSIM_TMRA1InputIndex, kSIM_TMRA1Input_XB_OUT39);

    /* PWM Select */
    /* xbar input 20.: xbar input 20, PWMA0_MUX_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN20Index, kSIM_XbarIn20PWMA0MuxTrig0);
    /* xbar input 21.: xbar input 21, PWMA0_MUX_TRIG1. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN21Index, kSIM_XbarIn21PWMA0MuxTrig1);
    /* xbar input 22.: xbar input 22, PWMA1_MUX_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN22Index, kSIM_XbarIn22PWMA1MuxTrig0);
    /* xbar input 24.: xbar input 24, PWMA2_MUX_TRIG0. */
    SIM_SetXbarInputPWMSelection(SIM, kSIM_XBARIN24Index, kSIM_XbarIn24PWMA2MuxTrig0);

    /* PWMA0_MUX_PWMB0_OUT_TRIG1 output assigned to XBARA_IN21 input is connected
     * to XBARA_OUT27 output assigned to PWMA3_EXT_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma0MuxPwmb0OutTrig1, kXBARA_OutputPwma3ExtSync);
    /* XB_IN7 output assigned to XBARA_IN7 input is connected
     * to XBARA_OUT29 output assigned to PWMA_PWMB_FAULT0 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbIn7, kXBARA_OutputPwmaPwmbFault0);
    /* CMPC_OUT output assigned to XBARA_IN14 input is connected
     * to XBARA_OUT38 output assigned to TA0_IN */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpcOut, kXBARA_OutputTa0In);
    /* CMPD_OUT output assigned to XBARA_IN15 input is connected
     * to XBARA_OUT39 output assigned to TA1_IN */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpdOut, kXBARA_OutputTa1In);
    /* EVTG2_OUTA output assigned to XBARA_IN42 input is connected
     * to XBARA_OUT4 output assigned to XB_OUT4 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg2Outa, kXBARA_OutputXbOut4);
    /* EVTG1_OUTA output assigned to XBARA_IN41 input is connected
     * to XBARA_OUT5 output assigned to XB_OUT5 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg1Outa, kXBARA_OutputXbOut5);
    /* AN0_LIMIT_TA0_OUT output assigned to XBARA_IN36 input is connected
     * to XBARA_OUT47 output assigned to EVTG0_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputAn0LimitTa0Out, kXBARA_OutputEvtg0A);
    /* AN1_LIMIT_TA1_OUT output assigned to XBARA_IN37 input is connected
     * to XBARA_OUT48 output assigned to EVTG0_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputAn1LimitTa1Out, kXBARA_OutputEvtg0B);
    /* AN2_LIMIT_TA2_OUT output assigned to XBARA_IN38 input is connected
     * to XBARA_OUT49 output assigned to EVTG0_C */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputAn2LimitTa2Out, kXBARA_OutputEvtg0C);
    /* AN3_LIMIT_TA3_OUT output assigned to XBARA_IN39 input is connected
     * to XBARA_OUT50 output assigned to EVTG0_D */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputAn3LimitTa3Out, kXBARA_OutputEvtg0D);
    /* PWMA0_MUX_PWMB0_OUT_TRIG0 output assigned to XBARA_IN20 input is connected
     * to XBARA_OUT51 output assigned to EVTG1_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma0MuxPwmb0OutTrig0, kXBARA_OutputEvtg1A);
    /* CMPC_OUT output assigned to XBARA_IN14 input is connected
     * to XBARA_OUT52 output assigned to EVTG1_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpcOut, kXBARA_OutputEvtg1B);
    /* PWMA1_MUX_PWMB1_OUT_TRIG0 output assigned to XBARA_IN22 input is connected
     * to XBARA_OUT55 output assigned to EVTG2_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma1MuxPwmb1OutTrig0, kXBARA_OutputEvtg2A);
    /* CMPD_OUT output assigned to XBARA_IN15 input is connected
     * to XBARA_OUT56 output assigned to EVTG2_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputCmpdOut, kXBARA_OutputEvtg2B);
    /* EVTG1_OUTB output assigned to XBARA_IN47 input is connected
     * to XBARA_OUT6 output assigned to XB_OUT6 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg1Outb, kXBARA_OutputXbOut6);
    /* EVTG2_OUTB output assigned to XBARA_IN48 input is connected
     * to XBARA_OUT7 output assigned to XB_OUT7 */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg2Outb, kXBARA_OutputXbOut7);
    /* PWMA2_MUX_PWMB2_OUT_TRIG0 output assigned to XBARA_IN24 input is connected
     * to XBARA_OUT12 output assigned to ADCA_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputPwma2MuxPwmb2OutTrig0, kXBARA_OutputAdcaSync);
    /* EVTG0_OUTB output assigned to XBARA_IN46 input is connected
     * to XBARA_OUT18 output assigned to CMPC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg0Outb, kXBARA_OutputCmpc);
    /* EVTG0_OUTA output assigned to XBARA_IN40 input is connected
     * to XBARA_OUT19 output assigned to CMPD */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputEvtg0Outa, kXBARA_OutputCmpd);
}


/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BDM_Config_Pin_deinit
 * Description   : This is a de-initialization function for 'BDM_Config_Pin' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 * END ****************************************************************************************************************/
void BDM_Config_Pin_deinit(void)
{
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOE IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOE);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* GPIO functionality on pin GPIOC0 (pin 3) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_DEINIT_User_LED_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC1 (pin 4) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_DEINIT_LED_HVP_GPIO, BDM_CONFIG_PIN_DEINIT_LED_HVP_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC5 (pin 18) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_DEINIT_XBAR_TP2_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP2_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC8 (pin 33) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_DEINIT_User_LED1_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED1_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC13 (pin 49) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_DEINIT_XBAR_TP1_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP1_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOC15 (pin 56) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_DEINIT_STB_EN_GPIO, BDM_CONFIG_PIN_DEINIT_STB_EN_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE0 (pin 45) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin0, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE1 (pin 46) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin1, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE2 (pin 47) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin2, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE3 (pin 48) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin3, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE4 (pin 51) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin4, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE5 (pin 52) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin5, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE6 (pin 53) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin6, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOE7 (pin 54) */
    GPIO_PinSetPeripheralMode(GPIOE, kGPIO_Pin7, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF0 (pin 36) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_DEINIT_XBAR_TP3_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP3_PIN_MASK, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF1 (pin 50) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin1, kGPIO_ModeGpio);
    /* GPIO functionality on pin GPIOF7 (pin 59) */
    GPIO_PinSetPeripheralMode(BDM_CONFIG_PIN_DEINIT_Load_SW_GPIO, BDM_CONFIG_PIN_DEINIT_Load_SW_PIN_MASK, kGPIO_ModeGpio);

    /* Initialize GPIO functionality on pin GPIOC0 (pin 3)  */
    GPIO_PinSetDirection(BDM_CONFIG_PIN_DEINIT_User_LED_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC1 (pin 4)  */
    GPIO_PinSetDirection(BDM_CONFIG_PIN_DEINIT_LED_HVP_GPIO, BDM_CONFIG_PIN_DEINIT_LED_HVP_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC5 (pin 18)  */
    GPIO_PinSetDirection(BDM_CONFIG_PIN_DEINIT_XBAR_TP2_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP2_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC8 (pin 33)  */
    GPIO_PinSetDirection(BDM_CONFIG_PIN_DEINIT_User_LED1_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED1_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC13 (pin 49)  */
    GPIO_PinSetDirection(BDM_CONFIG_PIN_DEINIT_XBAR_TP1_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP1_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOC15 (pin 56)  */
    GPIO_PinSetDirection(BDM_CONFIG_PIN_DEINIT_STB_EN_GPIO, BDM_CONFIG_PIN_DEINIT_STB_EN_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE0 (pin 45)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin0, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE1 (pin 46)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin1, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE2 (pin 47)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin2, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE3 (pin 48)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin3, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE4 (pin 51)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin4, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE5 (pin 52)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin5, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE6 (pin 53)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin6, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOE7 (pin 54)  */
    GPIO_PinSetDirection(GPIOE, kGPIO_Pin7, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOF0 (pin 36)  */
    GPIO_PinSetDirection(BDM_CONFIG_PIN_DEINIT_XBAR_TP3_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP3_PIN_MASK, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOF1 (pin 50)  */
    GPIO_PinSetDirection(GPIOF, kGPIO_Pin1, kGPIO_DigitalInput);

    /* Initialize GPIO functionality on pin GPIOF7 (pin 59)  */
    GPIO_PinSetDirection(BDM_CONFIG_PIN_DEINIT_Load_SW_GPIO, BDM_CONFIG_PIN_DEINIT_Load_SW_PIN_MASK, kGPIO_DigitalInput);

    /* Pin configuration on GPIOC0 (pin 3) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(BDM_CONFIG_PIN_DEINIT_User_LED_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED_PIN_MASK, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(BDM_CONFIG_PIN_DEINIT_User_LED_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED_PIN_MASK, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(BDM_CONFIG_PIN_DEINIT_User_LED_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED_PIN_MASK, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC1 (pin 4) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(BDM_CONFIG_PIN_DEINIT_LED_HVP_GPIO, BDM_CONFIG_PIN_DEINIT_LED_HVP_PIN_MASK, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(BDM_CONFIG_PIN_DEINIT_LED_HVP_GPIO, BDM_CONFIG_PIN_DEINIT_LED_HVP_PIN_MASK, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(BDM_CONFIG_PIN_DEINIT_LED_HVP_GPIO, BDM_CONFIG_PIN_DEINIT_LED_HVP_PIN_MASK, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC5 (pin 18) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(BDM_CONFIG_PIN_DEINIT_XBAR_TP2_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP2_PIN_MASK, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(BDM_CONFIG_PIN_DEINIT_XBAR_TP2_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP2_PIN_MASK, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(BDM_CONFIG_PIN_DEINIT_XBAR_TP2_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP2_PIN_MASK, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC8 (pin 33) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(BDM_CONFIG_PIN_DEINIT_User_LED1_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED1_PIN_MASK, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(BDM_CONFIG_PIN_DEINIT_User_LED1_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED1_PIN_MASK, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(BDM_CONFIG_PIN_DEINIT_User_LED1_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED1_PIN_MASK, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC13 (pin 49) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(BDM_CONFIG_PIN_DEINIT_XBAR_TP1_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP1_PIN_MASK, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(BDM_CONFIG_PIN_DEINIT_XBAR_TP1_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP1_PIN_MASK, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(BDM_CONFIG_PIN_DEINIT_XBAR_TP1_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP1_PIN_MASK, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOC15 (pin 56) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(BDM_CONFIG_PIN_DEINIT_STB_EN_GPIO, BDM_CONFIG_PIN_DEINIT_STB_EN_PIN_MASK, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(BDM_CONFIG_PIN_DEINIT_STB_EN_GPIO, BDM_CONFIG_PIN_DEINIT_STB_EN_PIN_MASK, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(BDM_CONFIG_PIN_DEINIT_STB_EN_GPIO, BDM_CONFIG_PIN_DEINIT_STB_EN_PIN_MASK, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE0 (pin 45) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin0, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin0, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin0, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE1 (pin 46) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin1, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin1, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin1, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE2 (pin 47) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin2, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin2, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin2, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE3 (pin 48) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin3, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin3, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin3, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE4 (pin 51) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin4, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin4, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin4, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE5 (pin 52) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin5, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin5, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin5, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE6 (pin 53) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin6, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin6, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin6, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOE7 (pin 54) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOE, kGPIO_Pin7, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOE, kGPIO_Pin7, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOE, kGPIO_Pin7, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOF0 (pin 36) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(BDM_CONFIG_PIN_DEINIT_XBAR_TP3_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP3_PIN_MASK, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(BDM_CONFIG_PIN_DEINIT_XBAR_TP3_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP3_PIN_MASK, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(BDM_CONFIG_PIN_DEINIT_XBAR_TP3_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP3_PIN_MASK, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOF1 (pin 50) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(GPIOF, kGPIO_Pin1, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(GPIOF, kGPIO_Pin1, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(GPIOF, kGPIO_Pin1, kGPIO_SlewRateSlow);

    /* Pin configuration on GPIOF7 (pin 59) */
    /* Pull-Pull/Open drain output mode configuration: Push pull output mode */
    GPIO_PinSetOutputMode(BDM_CONFIG_PIN_DEINIT_Load_SW_GPIO, BDM_CONFIG_PIN_DEINIT_Load_SW_PIN_MASK, kGPIO_OutputPushPull);
    /* Strength control configuration: Low drive strength is configured */
    GPIO_PinSetDriveStrength(BDM_CONFIG_PIN_DEINIT_Load_SW_GPIO, BDM_CONFIG_PIN_DEINIT_Load_SW_PIN_MASK, kGPIO_DriveStrengthLow);
    /* Slew rate control configuration: Slow slew rate is configured */
    GPIO_PinSetSlewRate(BDM_CONFIG_PIN_DEINIT_Load_SW_GPIO, BDM_CONFIG_PIN_DEINIT_Load_SW_PIN_MASK, kGPIO_SlewRateSlow);

    /* Interrupt configuration on GPIOC0 (pin 3): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(BDM_CONFIG_PIN_DEINIT_User_LED_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED_PIN_MASK, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC1 (pin 4): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(BDM_CONFIG_PIN_DEINIT_LED_HVP_GPIO, BDM_CONFIG_PIN_DEINIT_LED_HVP_PIN_MASK, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC5 (pin 18): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(BDM_CONFIG_PIN_DEINIT_XBAR_TP2_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP2_PIN_MASK, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC8 (pin 33): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(BDM_CONFIG_PIN_DEINIT_User_LED1_GPIO, BDM_CONFIG_PIN_DEINIT_User_LED1_PIN_MASK, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC13 (pin 49): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(BDM_CONFIG_PIN_DEINIT_XBAR_TP1_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP1_PIN_MASK, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOC15 (pin 56): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(BDM_CONFIG_PIN_DEINIT_STB_EN_GPIO, BDM_CONFIG_PIN_DEINIT_STB_EN_PIN_MASK, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE0 (pin 45): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin0, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE1 (pin 46): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin1, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE2 (pin 47): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin2, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE3 (pin 48): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin3, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE4 (pin 51): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin4, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE5 (pin 52): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin5, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE6 (pin 53): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin6, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOE7 (pin 54): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOE, kGPIO_Pin7, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOF0 (pin 36): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(BDM_CONFIG_PIN_DEINIT_XBAR_TP3_GPIO, BDM_CONFIG_PIN_DEINIT_XBAR_TP3_PIN_MASK, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOF1 (pin 50): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(GPIOF, kGPIO_Pin1, kGPIO_InterruptDisable);

    /* Interrupt configuration on GPIOF7 (pin 59): Interrupt is disabled */
    GPIO_PinSetInterruptConfig(BDM_CONFIG_PIN_DEINIT_Load_SW_GPIO, BDM_CONFIG_PIN_DEINIT_Load_SW_PIN_MASK, kGPIO_InterruptDisable);

    GPIOC->PUR =
        ((GPIOC->PUR &
          /* Mask bits to zero which are setting */
          (~(GPIO_PUR_PU_0_MASK | GPIO_PUR_PU_1_MASK | GPIO_PUR_PU_5_MASK | GPIO_PUR_PU_8_MASK | GPIO_PUR_PU_13_MASK | GPIO_PUR_PU_15_MASK)))

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_0_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_1_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_5_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_8_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_13_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_15_DISABLED));

    GPIOC->PUS =
        ((GPIOC->PUS &
          /* Mask bits to zero which are setting */
          (~(GPIO_PUS_PUS_0_MASK | GPIO_PUS_PUS_1_MASK | GPIO_PUS_PUS_5_MASK | GPIO_PUS_PUS_8_MASK | GPIO_PUS_PUS_13_MASK | GPIO_PUS_PUS_15_MASK)))

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_0_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_1_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_5_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_8_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_13_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_15_PULLUP));

    GPIOE->PUR =
        ((GPIOE->PUR &
          /* Mask bits to zero which are setting */
          (~(GPIO_PUR_PU_0_MASK | GPIO_PUR_PU_1_MASK | GPIO_PUR_PU_2_MASK | GPIO_PUR_PU_3_MASK | GPIO_PUR_PU_4_MASK | GPIO_PUR_PU_5_MASK | GPIO_PUR_PU_6_MASK | GPIO_PUR_PU_7_MASK)))

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_0_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_1_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_2_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_3_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_4_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_5_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_6_DISABLED)

         /* Pull Resistor Enable Bits: Pull resistor is disabled. */
         | GPIO_PUR_PU(PUR_PU_7_DISABLED));

    GPIOE->PUS =
        ((GPIOE->PUS &
          /* Mask bits to zero which are setting */
          (~(GPIO_PUS_PUS_0_MASK | GPIO_PUS_PUS_1_MASK | GPIO_PUS_PUS_2_MASK | GPIO_PUS_PUS_3_MASK | GPIO_PUS_PUS_4_MASK | GPIO_PUS_PUS_5_MASK | GPIO_PUS_PUS_6_MASK | GPIO_PUS_PUS_7_MASK)))

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_0_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_1_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_2_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_3_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_4_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_5_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_6_PULLUP)

         /* Pull Resistor Type Select Bits: Pullup resistor. */
         | GPIO_PUS_PUS(PUS_PUS_7_PULLUP));

    GPIOF->PUR = ((GPIOF->PUR &
                   /* Mask bits to zero which are setting */
                   (~(GPIO_PUR_PU_0_MASK | GPIO_PUR_PU_1_MASK | GPIO_PUR_PU_7_MASK)))

                  /* Pull Resistor Enable Bits: Pull resistor is disabled. */
                  | GPIO_PUR_PU(PUR_PU_0_DISABLED)

                  /* Pull Resistor Enable Bits: Pull resistor is disabled. */
                  | GPIO_PUR_PU(PUR_PU_1_DISABLED)

                  /* Pull Resistor Enable Bits: Pull resistor is disabled. */
                  | GPIO_PUR_PU(PUR_PU_7_DISABLED));

    GPIOF->PUS = ((GPIOF->PUS &
                   /* Mask bits to zero which are setting */
                   (~(GPIO_PUS_PUS_0_MASK | GPIO_PUS_PUS_1_MASK | GPIO_PUS_PUS_7_MASK)))

                  /* Pull Resistor Type Select Bits: Pullup resistor. */
                  | GPIO_PUS_PUS(PUS_PUS_0_PULLUP)

                  /* Pull Resistor Type Select Bits: Pullup resistor. */
                  | GPIO_PUS_PUS(PUS_PUS_1_PULLUP)

                  /* Pull Resistor Type Select Bits: Pullup resistor. */
                  | GPIO_PUS_PUS(PUS_PUS_7_PULLUP));
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT27 output assigned to PWMA3_EXT_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputPwma3ExtSync);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT47 output assigned to EVTG0_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg0A);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT48 output assigned to EVTG0_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg0B);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT49 output assigned to EVTG0_C */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg0C);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT50 output assigned to EVTG0_D */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg0D);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT51 output assigned to EVTG1_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg1A);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT52 output assigned to EVTG1_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg1B);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT55 output assigned to EVTG2_A */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg2A);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT56 output assigned to EVTG2_B */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputEvtg2B);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT12 output assigned to ADCA_SYNC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputAdcaSync);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT18 output assigned to CMPC */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputCmpc);
    /* VSS output assigned to XBARA_IN0 input is connected
     * to XBARA_OUT19 output assigned to CMPD */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputVss, kXBARA_OutputCmpd);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
Common_Config_Pin:
- options: {callFromInitBoot: 'true', coreID: core0, enableClock: 'true'}
- pin_list:
  - {pin_num: '58', peripheral: TMRB, signal: 'IN, 0', pin_signal: GPIOF6/TB2/PWMA_3X/PWMB_3X/XB_IN2}
  - {pin_num: '8', peripheral: TMRB, signal: 'IN, 1', pin_signal: GPIOC4/TA1/CMPB_O/XB_IN8/EWM_OUT_B}
  - {pin_num: '15', peripheral: ADC, signal: 'ANA, 2', pin_signal: GPIOA2/ANA2/VREFHA/CMPA_IN1}
  - {pin_num: '16', peripheral: ADC, signal: 'ANA, 3', pin_signal: GPIOA3/ANA3/VREFLA/CMPA_IN2}
  - {pin_num: '9', peripheral: ADC, signal: 'ANA, 7', pin_signal: GPIOA7/ANA7}
  - {pin_num: '24', peripheral: ADC, signal: 'ANB, 0', pin_signal: GPIOB0/ANB0/CMPB_IN3}
  - {pin_num: '25', peripheral: ADC, signal: 'ANB, 1', pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O}
  - {pin_num: '19', peripheral: ADC, signal: 'ANB, 6', pin_signal: GPIOB6/ANB6/CMPB_IN1}
  - {pin_num: '17', peripheral: ADC, signal: 'ANB, 7', pin_signal: GPIOB7/ANB7/CMPB_IN2}
  - {pin_num: '14', peripheral: CMPA, signal: 'IN, 0', pin_signal: GPIOA1/ANA1/CMPA_IN0}
  - {pin_num: '13', peripheral: CMPA, signal: 'IN, 3', pin_signal: GPIOA0/ANA0/CMPA_IN3/CMPC_O}
  - {pin_num: '25', peripheral: CMPB, signal: 'IN, 0', pin_signal: GPIOB1/ANB1/CMPB_IN0/DACB_O}
  - {pin_num: '17', peripheral: CMPB, signal: 'IN, 2', pin_signal: GPIOB7/ANB7/CMPB_IN2}
  - {pin_num: '24', peripheral: CMPB, signal: 'IN, 3', pin_signal: GPIOB0/ANB0/CMPB_IN3}
  - {pin_num: '21', peripheral: CMPC, signal: 'IN, 1', pin_signal: GPIOB4/ANB4/CMPC_IN1}
  - {pin_num: '20', peripheral: CMPC, signal: 'IN, 2', pin_signal: GPIOB5/ANB5/CMPC_IN2}
  - {pin_num: '27', peripheral: CMPC, signal: 'IN, 3', pin_signal: GPIOB2/ANB2/VREFHB/CMPC_IN3}
  - {pin_num: '12', peripheral: CMPD, signal: 'IN, 0', pin_signal: GPIOA4/ANA4/CMPD_IN0}
  - {pin_num: '4', peripheral: GPIOC, signal: 'GPIO, 1', pin_signal: GPIOC1/XTAL, direction: OUTPUT}
  - {pin_num: '38', peripheral: QSCI1, signal: RXD, pin_signal: GPIOC12/CANRX/SDA1/RXD1}
  - {pin_num: '37', peripheral: QSCI1, signal: TXD, pin_signal: GPIOC11/CANTX/SCL1/TXD1}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : Common_Config_Pin
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
void Common_Config_Pin(void)
{
    /* GPIOA IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOA);
    /* GPIOB IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOB);
    /* GPIOC IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOC);
    /* GPIOF IPBus Clock Enable: The peripheral is clocked. */
    CLOCK_EnableClock(kCLOCK_GPIOF);
    /* Enable peripheral functionality on pin GPIOA0 (pin 13) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOA0 (pin 13) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_A0_ANA0_and_CMPA_IN3);
    /* Enable peripheral functionality on pin GPIOA1 (pin 14) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOA2 (pin 15) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOA3 (pin 16) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin3, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOA4 (pin 12) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOA7 (pin 9) */
    GPIO_PinSetPeripheralMode(GPIOA, kGPIO_Pin7, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB0 (pin 24) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin0, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB1 (pin 25) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin1, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOB1 (pin 25) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_B1_ANB1_and_CMPB_IN0);
    /* Enable peripheral functionality on pin GPIOB2 (pin 27) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin2, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB4 (pin 21) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB5 (pin 20) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin5, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB6 (pin 19) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin6, kGPIO_ModePeripheral);
    /* Enable peripheral functionality on pin GPIOB7 (pin 17) */
    GPIO_PinSetPeripheralMode(GPIOB, kGPIO_Pin7, kGPIO_ModePeripheral);
    /* GPIO functionality on pin GPIOC1 (pin 4) */
    GPIO_PinSetPeripheralMode(COMMON_CONFIG_PIN_LED_HVP_GPIO, COMMON_CONFIG_PIN_LED_HVP_PIN_MASK, kGPIO_ModeGpio);
    /* Enable peripheral functionality on pin GPIOC4 (pin 8) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin4, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC4 (pin 8) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C4_XB_IN8);
    /* Enable peripheral functionality on pin GPIOC11 (pin 37) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin11, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC11 (pin 37) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C11_TXD1);
    /* Enable peripheral functionality on pin GPIOC12 (pin 38) */
    GPIO_PinSetPeripheralMode(GPIOC, kGPIO_Pin12, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOC12 (pin 38) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_C12_RXD1);
    /* Enable peripheral functionality on pin GPIOF6 (pin 58) */
    GPIO_PinSetPeripheralMode(GPIOF, kGPIO_Pin6, kGPIO_ModePeripheral);
    /* Peripheral functionality on pin GPIOF6 (pin 58) */
    GPIO_PinSetPeripheralMux(kGPIO_Peri_F6_XB_IN2);

    /* Initialize GPIO functionality on pin GPIOC1 (pin 4)  */
    GPIO_PinWrite(COMMON_CONFIG_PIN_LED_HVP_GPIO, COMMON_CONFIG_PIN_LED_HVP_PIN_MASK, kGPIO_OutputLow);
    GPIO_PinSetDirection(COMMON_CONFIG_PIN_LED_HVP_GPIO, COMMON_CONFIG_PIN_LED_HVP_PIN_MASK, kGPIO_DigitalOutput);

    /* Internal Peripheral Select */
    /* Select TMRB0 Input.: Select TMRB0 Input, XB_OUT34. */
    SIM_SetInternalPeriInput(SIM, kSIM_TMRB0InputIndex, kSIM_TMRB0Input_XB_OUT34);
    /* Select TMRB1 Input.: Select TMRB1 Input, XB_OUT35. */
    SIM_SetInternalPeriInput(SIM, kSIM_TMRB1InputIndex, kSIM_TMRB1Input_XB_OUT35);

    /* XB_IN2 output assigned to XBARA_IN2 input is connected
     * to XBARA_OUT34 output assigned to TB0_IN */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbIn2, kXBARA_OutputTb0In);
    /* XB_IN8 output assigned to XBARA_IN8 input is connected
     * to XBARA_OUT35 output assigned to TB1_IN */
    XBARA_SetSignalsConnection(XBARA, kXBARA_InputXbIn8, kXBARA_OutputTb1In);
}
/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
