/*
 * Copyright 2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

/*! @name GPIOF7 (number 59), Load_SW
  @{ */
#define BOARD_Load_SW_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BOARD_Load_SW_PIN 7U              /*!<@brief GPIOF pin index: 7 */
#define BOARD_Load_SW_PIN_MASK kGPIO_Pin7 /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name GPIOC15 (number 56), STB_EN
  @{ */
#define BOARD_STB_EN_GPIO GPIOC           /*!<@brief GPIO device name: GPIOC */
#define BOARD_STB_EN_PIN 15U              /*!<@brief GPIOC pin index: 15 */
#define BOARD_STB_EN_PIN_MASK kGPIO_Pin15 /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name GPIOC0 (number 3), User_LED
  @{ */
#define BOARD_User_LED_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_User_LED_PIN 0U              /*!<@brief GPIOC pin index: 0 */
#define BOARD_User_LED_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name GPIOC8 (number 33), User_LED1
  @{ */
#define BOARD_User_LED1_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_User_LED1_PIN 8U              /*!<@brief GPIOC pin index: 8 */
#define BOARD_User_LED1_PIN_MASK kGPIO_Pin8 /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name GPIOC13 (number 49), XBAR_TP1
  @{ */
#define BOARD_XBAR_TP1_GPIO GPIOC           /*!<@brief GPIO device name: GPIOC */
#define BOARD_XBAR_TP1_PIN 13U              /*!<@brief GPIOC pin index: 13 */
#define BOARD_XBAR_TP1_PIN_MASK kGPIO_Pin13 /*!<@brief PORT pin mask */
                                            /* @} */

/*! @name GPIOC5 (number 18), XBAR_TP2
  @{ */
#define BOARD_XBAR_TP2_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_XBAR_TP2_PIN 5U              /*!<@brief GPIOC pin index: 5 */
#define BOARD_XBAR_TP2_PIN_MASK kGPIO_Pin5 /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name GPIOF0 (number 36), XBAR_TP3
  @{ */
#define BOARD_XBAR_TP3_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BOARD_XBAR_TP3_PIN 0U              /*!<@brief GPIOF pin index: 0 */
#define BOARD_XBAR_TP3_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                           /* @} */

/*! @name GPIOC1 (number 4), LED_HVP
  @{ */
#define BOARD_LED_HVP_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_LED_HVP_PIN 1U              /*!<@brief GPIOC pin index: 1 */
#define BOARD_LED_HVP_PIN_MASK kGPIO_Pin1 /*!<@brief PORT pin mask */
                                          /* @} */

/*! @name GPIOC7 (number 32), XBAR_TP4
  @{ */
#define BOARD_XBAR_TP4_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BOARD_XBAR_TP4_PIN 7U              /*!<@brief GPIOC pin index: 7 */
#define BOARD_XBAR_TP4_PIN_MASK kGPIO_Pin7 /*!<@brief PORT pin mask */
                                           /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BCM_Config_Pin(void);

#define GPIO_PUR_PU_0_MASK 0x01u     /*!<@brief Pull Resistor Enable Bits Mask for item 0. */
#define GPIO_PUR_PU_13_MASK 0x2000u  /*!<@brief Pull Resistor Enable Bits Mask for item 13. */
#define GPIO_PUR_PU_15_MASK 0x8000u  /*!<@brief Pull Resistor Enable Bits Mask for item 15. */
#define GPIO_PUR_PU_1_MASK 0x02u     /*!<@brief Pull Resistor Enable Bits Mask for item 1. */
#define GPIO_PUR_PU_2_MASK 0x04u     /*!<@brief Pull Resistor Enable Bits Mask for item 2. */
#define GPIO_PUR_PU_3_MASK 0x08u     /*!<@brief Pull Resistor Enable Bits Mask for item 3. */
#define GPIO_PUR_PU_4_MASK 0x10u     /*!<@brief Pull Resistor Enable Bits Mask for item 4. */
#define GPIO_PUR_PU_5_MASK 0x20u     /*!<@brief Pull Resistor Enable Bits Mask for item 5. */
#define GPIO_PUR_PU_6_MASK 0x40u     /*!<@brief Pull Resistor Enable Bits Mask for item 6. */
#define GPIO_PUR_PU_7_MASK 0x80u     /*!<@brief Pull Resistor Enable Bits Mask for item 7. */
#define GPIO_PUR_PU_8_MASK 0x0100u   /*!<@brief Pull Resistor Enable Bits Mask for item 8. */
#define GPIO_PUS_PUS_0_MASK 0x01u    /*!<@brief Pull Resistor Type Select Bits Mask for item 0. */
#define GPIO_PUS_PUS_13_MASK 0x2000u /*!<@brief Pull Resistor Type Select Bits Mask for item 13. */
#define GPIO_PUS_PUS_15_MASK 0x8000u /*!<@brief Pull Resistor Type Select Bits Mask for item 15. */
#define GPIO_PUS_PUS_1_MASK 0x02u    /*!<@brief Pull Resistor Type Select Bits Mask for item 1. */
#define GPIO_PUS_PUS_2_MASK 0x04u    /*!<@brief Pull Resistor Type Select Bits Mask for item 2. */
#define GPIO_PUS_PUS_3_MASK 0x08u    /*!<@brief Pull Resistor Type Select Bits Mask for item 3. */
#define GPIO_PUS_PUS_4_MASK 0x10u    /*!<@brief Pull Resistor Type Select Bits Mask for item 4. */
#define GPIO_PUS_PUS_5_MASK 0x20u    /*!<@brief Pull Resistor Type Select Bits Mask for item 5. */
#define GPIO_PUS_PUS_6_MASK 0x40u    /*!<@brief Pull Resistor Type Select Bits Mask for item 6. */
#define GPIO_PUS_PUS_7_MASK 0x80u    /*!<@brief Pull Resistor Type Select Bits Mask for item 7. */
#define GPIO_PUS_PUS_8_MASK 0x0100u  /*!<@brief Pull Resistor Type Select Bits Mask for item 8. */
#define PUR_PU_0_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_13_DISABLED 0x00u     /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_15_DISABLED 0x00u     /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_1_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_2_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_3_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_4_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_5_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_6_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_7_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_8_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUS_PUS_0_PULLUP 0x01u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_13_PULLUP 0x2000u    /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_15_PULLUP 0x8000u    /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_1_PULLUP 0x02u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_2_PULLUP 0x04u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_3_PULLUP 0x08u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_4_PULLUP 0x10u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_5_PULLUP 0x20u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_6_PULLUP 0x40u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_7_PULLUP 0x80u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_8_PULLUP 0x0100u     /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */

/*!
 * @brief This is a de-initialization function for 'BCM_Config_Pin' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void BCM_Config_Pin_deinit(void);

/*! @name GPIOF0 (number 36), XBAR_TP3
  @{ */
#define BDM_CONFIG_PIN_XBAR_TP3_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BDM_CONFIG_PIN_XBAR_TP3_PIN 0U              /*!<@brief GPIOF pin index: 0 */
#define BDM_CONFIG_PIN_XBAR_TP3_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name GPIOF7 (number 59), Load_SW
  @{ */
#define BDM_CONFIG_PIN_Load_SW_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BDM_CONFIG_PIN_Load_SW_PIN 7U              /*!<@brief GPIOF pin index: 7 */
#define BDM_CONFIG_PIN_Load_SW_PIN_MASK kGPIO_Pin7 /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name GPIOC0 (number 3), User_LED
  @{ */
#define BDM_CONFIG_PIN_User_LED_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_User_LED_PIN 0U              /*!<@brief GPIOC pin index: 0 */
#define BDM_CONFIG_PIN_User_LED_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name GPIOC1 (number 4), LED_HVP
  @{ */
#define BDM_CONFIG_PIN_LED_HVP_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_LED_HVP_PIN 1U              /*!<@brief GPIOC pin index: 1 */
#define BDM_CONFIG_PIN_LED_HVP_PIN_MASK kGPIO_Pin1 /*!<@brief PORT pin mask */
                                                   /* @} */

/*! @name GPIOC5 (number 18), XBAR_TP2
  @{ */
#define BDM_CONFIG_PIN_XBAR_TP2_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_XBAR_TP2_PIN 5U              /*!<@brief GPIOC pin index: 5 */
#define BDM_CONFIG_PIN_XBAR_TP2_PIN_MASK kGPIO_Pin5 /*!<@brief PORT pin mask */
                                                    /* @} */

/*! @name GPIOC8 (number 33), User_LED1
  @{ */
#define BDM_CONFIG_PIN_User_LED1_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_User_LED1_PIN 8U              /*!<@brief GPIOC pin index: 8 */
#define BDM_CONFIG_PIN_User_LED1_PIN_MASK kGPIO_Pin8 /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name GPIOC13 (number 49), XBAR_TP1
  @{ */
#define BDM_CONFIG_PIN_XBAR_TP1_GPIO GPIOC           /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_XBAR_TP1_PIN 13U              /*!<@brief GPIOC pin index: 13 */
#define BDM_CONFIG_PIN_XBAR_TP1_PIN_MASK kGPIO_Pin13 /*!<@brief PORT pin mask */
                                                     /* @} */

/*! @name GPIOC15 (number 56), STB_EN
  @{ */
#define BDM_CONFIG_PIN_STB_EN_GPIO GPIOC           /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_STB_EN_PIN 15U              /*!<@brief GPIOC pin index: 15 */
#define BDM_CONFIG_PIN_STB_EN_PIN_MASK kGPIO_Pin15 /*!<@brief PORT pin mask */
                                                   /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BDM_Config_Pin(void);

#define GPIO_PUR_PU_0_MASK 0x01u     /*!<@brief Pull Resistor Enable Bits Mask for item 0. */
#define GPIO_PUR_PU_13_MASK 0x2000u  /*!<@brief Pull Resistor Enable Bits Mask for item 13. */
#define GPIO_PUR_PU_15_MASK 0x8000u  /*!<@brief Pull Resistor Enable Bits Mask for item 15. */
#define GPIO_PUR_PU_1_MASK 0x02u     /*!<@brief Pull Resistor Enable Bits Mask for item 1. */
#define GPIO_PUR_PU_2_MASK 0x04u     /*!<@brief Pull Resistor Enable Bits Mask for item 2. */
#define GPIO_PUR_PU_3_MASK 0x08u     /*!<@brief Pull Resistor Enable Bits Mask for item 3. */
#define GPIO_PUR_PU_4_MASK 0x10u     /*!<@brief Pull Resistor Enable Bits Mask for item 4. */
#define GPIO_PUR_PU_5_MASK 0x20u     /*!<@brief Pull Resistor Enable Bits Mask for item 5. */
#define GPIO_PUR_PU_6_MASK 0x40u     /*!<@brief Pull Resistor Enable Bits Mask for item 6. */
#define GPIO_PUR_PU_7_MASK 0x80u     /*!<@brief Pull Resistor Enable Bits Mask for item 7. */
#define GPIO_PUR_PU_8_MASK 0x0100u   /*!<@brief Pull Resistor Enable Bits Mask for item 8. */
#define GPIO_PUS_PUS_0_MASK 0x01u    /*!<@brief Pull Resistor Type Select Bits Mask for item 0. */
#define GPIO_PUS_PUS_13_MASK 0x2000u /*!<@brief Pull Resistor Type Select Bits Mask for item 13. */
#define GPIO_PUS_PUS_15_MASK 0x8000u /*!<@brief Pull Resistor Type Select Bits Mask for item 15. */
#define GPIO_PUS_PUS_1_MASK 0x02u    /*!<@brief Pull Resistor Type Select Bits Mask for item 1. */
#define GPIO_PUS_PUS_2_MASK 0x04u    /*!<@brief Pull Resistor Type Select Bits Mask for item 2. */
#define GPIO_PUS_PUS_3_MASK 0x08u    /*!<@brief Pull Resistor Type Select Bits Mask for item 3. */
#define GPIO_PUS_PUS_4_MASK 0x10u    /*!<@brief Pull Resistor Type Select Bits Mask for item 4. */
#define GPIO_PUS_PUS_5_MASK 0x20u    /*!<@brief Pull Resistor Type Select Bits Mask for item 5. */
#define GPIO_PUS_PUS_6_MASK 0x40u    /*!<@brief Pull Resistor Type Select Bits Mask for item 6. */
#define GPIO_PUS_PUS_7_MASK 0x80u    /*!<@brief Pull Resistor Type Select Bits Mask for item 7. */
#define GPIO_PUS_PUS_8_MASK 0x0100u  /*!<@brief Pull Resistor Type Select Bits Mask for item 8. */
#define PUR_PU_0_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_13_DISABLED 0x00u     /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_15_DISABLED 0x00u     /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_1_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_2_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_3_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_4_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_5_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_6_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_7_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUR_PU_8_DISABLED 0x00u      /*!<@brief Pull Resistor Enable Bits: Pull resistor is disabled */
#define PUS_PUS_0_PULLUP 0x01u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_13_PULLUP 0x2000u    /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_15_PULLUP 0x8000u    /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_1_PULLUP 0x02u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_2_PULLUP 0x04u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_3_PULLUP 0x08u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_4_PULLUP 0x10u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_5_PULLUP 0x20u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_6_PULLUP 0x40u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_7_PULLUP 0x80u       /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */
#define PUS_PUS_8_PULLUP 0x0100u     /*!<@brief Pull Resistor Type Select Bits: Pullup resistor */

/*! @name GPIOF0 (number 36), XBAR_TP3
  @{ */
#define BDM_CONFIG_PIN_DEINIT_XBAR_TP3_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BDM_CONFIG_PIN_DEINIT_XBAR_TP3_PIN 0U              /*!<@brief GPIOF pin index: 0 */
#define BDM_CONFIG_PIN_DEINIT_XBAR_TP3_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name GPIOF7 (number 59), Load_SW
  @{ */
#define BDM_CONFIG_PIN_DEINIT_Load_SW_GPIO GPIOF          /*!<@brief GPIO device name: GPIOF */
#define BDM_CONFIG_PIN_DEINIT_Load_SW_PIN 7U              /*!<@brief GPIOF pin index: 7 */
#define BDM_CONFIG_PIN_DEINIT_Load_SW_PIN_MASK kGPIO_Pin7 /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name GPIOC0 (number 3), User_LED
  @{ */
#define BDM_CONFIG_PIN_DEINIT_User_LED_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_DEINIT_User_LED_PIN 0U              /*!<@brief GPIOC pin index: 0 */
#define BDM_CONFIG_PIN_DEINIT_User_LED_PIN_MASK kGPIO_Pin0 /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name GPIOC1 (number 4), LED_HVP
  @{ */
#define BDM_CONFIG_PIN_DEINIT_LED_HVP_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_DEINIT_LED_HVP_PIN 1U              /*!<@brief GPIOC pin index: 1 */
#define BDM_CONFIG_PIN_DEINIT_LED_HVP_PIN_MASK kGPIO_Pin1 /*!<@brief PORT pin mask */
                                                          /* @} */

/*! @name GPIOC5 (number 18), XBAR_TP2
  @{ */
#define BDM_CONFIG_PIN_DEINIT_XBAR_TP2_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_DEINIT_XBAR_TP2_PIN 5U              /*!<@brief GPIOC pin index: 5 */
#define BDM_CONFIG_PIN_DEINIT_XBAR_TP2_PIN_MASK kGPIO_Pin5 /*!<@brief PORT pin mask */
                                                           /* @} */

/*! @name GPIOC8 (number 33), User_LED1
  @{ */
#define BDM_CONFIG_PIN_DEINIT_User_LED1_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_DEINIT_User_LED1_PIN 8U              /*!<@brief GPIOC pin index: 8 */
#define BDM_CONFIG_PIN_DEINIT_User_LED1_PIN_MASK kGPIO_Pin8 /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name GPIOC13 (number 49), XBAR_TP1
  @{ */
#define BDM_CONFIG_PIN_DEINIT_XBAR_TP1_GPIO GPIOC           /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_DEINIT_XBAR_TP1_PIN 13U              /*!<@brief GPIOC pin index: 13 */
#define BDM_CONFIG_PIN_DEINIT_XBAR_TP1_PIN_MASK kGPIO_Pin13 /*!<@brief PORT pin mask */
                                                            /* @} */

/*! @name GPIOC15 (number 56), STB_EN
  @{ */
#define BDM_CONFIG_PIN_DEINIT_STB_EN_GPIO GPIOC           /*!<@brief GPIO device name: GPIOC */
#define BDM_CONFIG_PIN_DEINIT_STB_EN_PIN 15U              /*!<@brief GPIOC pin index: 15 */
#define BDM_CONFIG_PIN_DEINIT_STB_EN_PIN_MASK kGPIO_Pin15 /*!<@brief PORT pin mask */
                                                          /* @} */

/*!
 * @brief This is a de-initialization function for 'BDM_Config_Pin' function.
 * It sets all pins features (routing, direction and electrical) to their after-reset state.
 * It also tries to route the previous peripheral signals to their default pins.
 *
 */
void BDM_Config_Pin_deinit(void);

/*! @name GPIOC1 (number 4), LED_HVP
  @{ */
#define COMMON_CONFIG_PIN_LED_HVP_GPIO GPIOC          /*!<@brief GPIO device name: GPIOC */
#define COMMON_CONFIG_PIN_LED_HVP_PIN 1U              /*!<@brief GPIOC pin index: 1 */
#define COMMON_CONFIG_PIN_LED_HVP_PIN_MASK kGPIO_Pin1 /*!<@brief PORT pin mask */
                                                      /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void Common_Config_Pin(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
